version: "3"

services:
  app:
    image: memochou1993/distributed-chatroom
    container_name: app
    depends_on:
      - redis
    restart: always
    env_file:
      - .env
    ports:
      - "80:80"
    networks:
      - backend
  redis:
    image: redis:latest
    container_name: distributed-chatroom-redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - backend

networks:
  backend:
